name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build-deploy-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      run: |
        mvn clean install
        curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline started"}' https://hooks.slack.com/services/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

              
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 13.235.71.124
        username: ubuntu
        key: ${{ secrets.GFL_BACKEND_KEY }}
        source: "target/*.jar"
        target: "builds"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 13.235.71.124
        username: ubuntu
        key: ${{ secrets.GFL_BACKEND_KEY }}
        script: |
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          java -jar /home/ubuntu/builds/target/*.jar > /home/ubuntu/builds/target/server-logs.txt 2>&1 &
          
          
    - name: slack the message for success
      if: success()
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline succeeded"}' https://hooks.slack.com/services/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
      
    - name: slack the message for faliure
      if: failure()
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline failed"}' https://hooks.slack.com/services/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
          
                   
