name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-deploy-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      run: mvn clean install
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 13.235.71.124
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        source: "target/*.jar"
        target: "builds"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 13.235.71.124
        username: ubuntu
        key: ${{ secrets.SSH_KEY }}
        script: |
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          java -jar /home/ubuntu/builds/target/*.jar > /home/ubuntu/builds/target/server-logs.txt 2>&1 &
