name: V2 Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build-deploy-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"V2 Back end pipeline started"}' https://hooks.slack.com/services/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
        mvn clean install
        
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 150.107.188.188
        username: ${{ secrets.GFL_SSH_USER }}
        password: ${{ secrets.GFL_SSH_PASSWORD }}
        source: "target/*.jar"
        target: "server/builds"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 150.107.188.188
        username: ${{ secrets.GFL_SSH_USER }}
        password: ${{ secrets.GFL_SSH_PASSWORD }}
        script: |
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          java -jar /home/${{ secrets.GFL_SSH_USER }}/server/builds/target/*.jar > /home/${{ secrets.GFL_SSH_USER }}/server/builds/target/server-logs.txt 2>&1 &
          
          
    - name: slack the message for success
      if: success()
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"V2 Back end pipeline succeeded"}' https://hooks.slack.com/services/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
      
    - name: slack the message for faliure
      if: failure()
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"V2 Back end pipeline failed"}' https://hooks.slack.com/services/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
