name: Java CI with Maven For Palsana

on:
  push:
    branches: [ master ]

jobs:
  build-deploy-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      run: |
        sudo bash ./setenv.sh application.palsana
        mvn clean install
        #curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline started"}' https://hooks.slack.com/services/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
              
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 103.137.194.167
        username: gloryauto
        password: ${{ secrets.GFL_P_PASSWORD }}
        source: "target/*.jar"
        target: "dyeing_erp"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 103.137.194.167
        username: gloryauto
        password: ${{ secrets.GFL_P_PASSWORD }}
        script: |
          sudo rm *.jar
          fuser -n tcp -k 8080 
          fuser -n tcp -k 8080 
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          java -jar /home/gloryauto/dyeing_erp/target/*.jar > /home/gloryauto/dyeing_erp/target/server-logs.txt 2>&1 &
          
    - name: slack the message for success
      if: success()
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline succeeded for palsana server"}' https://hooks.slack.com/services/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
    - name: slack the message for faliure
      if: failure()
      run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline failed for palsana server"}' https://hooks.slack.com/services/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
          
