name: Java CI with Maven For Palsana

on:
  push:
    branches: [ master ]

jobs:
  build-deploy-run:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - name: Build with Maven
      run: |
        sudo bash ./setenv.sh application.palsana
        mvn clean install
        #curl -X POST -H 'Content-type: application/json' --data '{"text":"Back end pipeline started"}' https://hooks.slack.com/services/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
              
    - name: copy file via ssh key
      uses: appleboy/scp-action@master
      with:
        host: 103.137.194.167
        username: gloryauto
        key: 123456
        source: "target/*.jar"
        target: "builds"
        
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.3
      with:
        host: 103.137.194.167
        username: gloryauto
        key: 123456
        script: |
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          fuser -k -n tcp 8080
          java -jar /home/ubuntu/builds/target/*.jar > /home/ubuntu/builds/target/se
